// Generated by gencpp from file bb8_action_pkg/CustomActionMsgResult.msg
// DO NOT EDIT!


#ifndef BB8_ACTION_PKG_MESSAGE_CUSTOMACTIONMSGRESULT_H
#define BB8_ACTION_PKG_MESSAGE_CUSTOMACTIONMSGRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bb8_action_pkg
{
template <class ContainerAllocator>
struct CustomActionMsgResult_
{
  typedef CustomActionMsgResult_<ContainerAllocator> Type;

  CustomActionMsgResult_()
    : result()  {
    }
  CustomActionMsgResult_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::bb8_action_pkg::CustomActionMsgResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bb8_action_pkg::CustomActionMsgResult_<ContainerAllocator> const> ConstPtr;

}; // struct CustomActionMsgResult_

typedef ::bb8_action_pkg::CustomActionMsgResult_<std::allocator<void> > CustomActionMsgResult;

typedef boost::shared_ptr< ::bb8_action_pkg::CustomActionMsgResult > CustomActionMsgResultPtr;
typedef boost::shared_ptr< ::bb8_action_pkg::CustomActionMsgResult const> CustomActionMsgResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bb8_action_pkg::CustomActionMsgResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bb8_action_pkg::CustomActionMsgResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bb8_action_pkg::CustomActionMsgResult_<ContainerAllocator1> & lhs, const ::bb8_action_pkg::CustomActionMsgResult_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bb8_action_pkg::CustomActionMsgResult_<ContainerAllocator1> & lhs, const ::bb8_action_pkg::CustomActionMsgResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bb8_action_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bb8_action_pkg::CustomActionMsgResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bb8_action_pkg::CustomActionMsgResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bb8_action_pkg::CustomActionMsgResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bb8_action_pkg::CustomActionMsgResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bb8_action_pkg::CustomActionMsgResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bb8_action_pkg::CustomActionMsgResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bb8_action_pkg::CustomActionMsgResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::bb8_action_pkg::CustomActionMsgResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::bb8_action_pkg::CustomActionMsgResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bb8_action_pkg/CustomActionMsgResult";
  }

  static const char* value(const ::bb8_action_pkg::CustomActionMsgResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bb8_action_pkg::CustomActionMsgResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"string result\n"
;
  }

  static const char* value(const ::bb8_action_pkg::CustomActionMsgResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bb8_action_pkg::CustomActionMsgResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomActionMsgResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bb8_action_pkg::CustomActionMsgResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bb8_action_pkg::CustomActionMsgResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BB8_ACTION_PKG_MESSAGE_CUSTOMACTIONMSGRESULT_H
