// Generated by gencpp from file bb8_service_pkg/bb8ServiceMessage.msg
// DO NOT EDIT!


#ifndef BB8_SERVICE_PKG_MESSAGE_BB8SERVICEMESSAGE_H
#define BB8_SERVICE_PKG_MESSAGE_BB8SERVICEMESSAGE_H

#include <ros/service_traits.h>


#include <bb8_service_pkg/bb8ServiceMessageRequest.h>
#include <bb8_service_pkg/bb8ServiceMessageResponse.h>


namespace bb8_service_pkg
{

struct bb8ServiceMessage
{

typedef bb8ServiceMessageRequest Request;
typedef bb8ServiceMessageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct bb8ServiceMessage
} // namespace bb8_service_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bb8_service_pkg::bb8ServiceMessage > {
  static const char* value()
  {
    return "031d24522d462b2314fd1b6270670dd2";
  }

  static const char* value(const ::bb8_service_pkg::bb8ServiceMessage&) { return value(); }
};

template<>
struct DataType< ::bb8_service_pkg::bb8ServiceMessage > {
  static const char* value()
  {
    return "bb8_service_pkg/bb8ServiceMessage";
  }

  static const char* value(const ::bb8_service_pkg::bb8ServiceMessage&) { return value(); }
};


// service_traits::MD5Sum< ::bb8_service_pkg::bb8ServiceMessageRequest> should match
// service_traits::MD5Sum< ::bb8_service_pkg::bb8ServiceMessage >
template<>
struct MD5Sum< ::bb8_service_pkg::bb8ServiceMessageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bb8_service_pkg::bb8ServiceMessage >::value();
  }
  static const char* value(const ::bb8_service_pkg::bb8ServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bb8_service_pkg::bb8ServiceMessageRequest> should match
// service_traits::DataType< ::bb8_service_pkg::bb8ServiceMessage >
template<>
struct DataType< ::bb8_service_pkg::bb8ServiceMessageRequest>
{
  static const char* value()
  {
    return DataType< ::bb8_service_pkg::bb8ServiceMessage >::value();
  }
  static const char* value(const ::bb8_service_pkg::bb8ServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bb8_service_pkg::bb8ServiceMessageResponse> should match
// service_traits::MD5Sum< ::bb8_service_pkg::bb8ServiceMessage >
template<>
struct MD5Sum< ::bb8_service_pkg::bb8ServiceMessageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bb8_service_pkg::bb8ServiceMessage >::value();
  }
  static const char* value(const ::bb8_service_pkg::bb8ServiceMessageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bb8_service_pkg::bb8ServiceMessageResponse> should match
// service_traits::DataType< ::bb8_service_pkg::bb8ServiceMessage >
template<>
struct DataType< ::bb8_service_pkg::bb8ServiceMessageResponse>
{
  static const char* value()
  {
    return DataType< ::bb8_service_pkg::bb8ServiceMessage >::value();
  }
  static const char* value(const ::bb8_service_pkg::bb8ServiceMessageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BB8_SERVICE_PKG_MESSAGE_BB8SERVICEMESSAGE_H
