// Generated by gencpp from file bb8_service_pkg/bb8ServiceMessageResponse.msg
// DO NOT EDIT!


#ifndef BB8_SERVICE_PKG_MESSAGE_BB8SERVICEMESSAGERESPONSE_H
#define BB8_SERVICE_PKG_MESSAGE_BB8SERVICEMESSAGERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bb8_service_pkg
{
template <class ContainerAllocator>
struct bb8ServiceMessageResponse_
{
  typedef bb8ServiceMessageResponse_<ContainerAllocator> Type;

  bb8ServiceMessageResponse_()
    : success(false)  {
    }
  bb8ServiceMessageResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::bb8_service_pkg::bb8ServiceMessageResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bb8_service_pkg::bb8ServiceMessageResponse_<ContainerAllocator> const> ConstPtr;

}; // struct bb8ServiceMessageResponse_

typedef ::bb8_service_pkg::bb8ServiceMessageResponse_<std::allocator<void> > bb8ServiceMessageResponse;

typedef boost::shared_ptr< ::bb8_service_pkg::bb8ServiceMessageResponse > bb8ServiceMessageResponsePtr;
typedef boost::shared_ptr< ::bb8_service_pkg::bb8ServiceMessageResponse const> bb8ServiceMessageResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bb8_service_pkg::bb8ServiceMessageResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bb8_service_pkg::bb8ServiceMessageResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bb8_service_pkg::bb8ServiceMessageResponse_<ContainerAllocator1> & lhs, const ::bb8_service_pkg::bb8ServiceMessageResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bb8_service_pkg::bb8ServiceMessageResponse_<ContainerAllocator1> & lhs, const ::bb8_service_pkg::bb8ServiceMessageResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bb8_service_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bb8_service_pkg::bb8ServiceMessageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bb8_service_pkg::bb8ServiceMessageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bb8_service_pkg::bb8ServiceMessageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bb8_service_pkg::bb8ServiceMessageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bb8_service_pkg::bb8ServiceMessageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bb8_service_pkg::bb8ServiceMessageResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bb8_service_pkg::bb8ServiceMessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::bb8_service_pkg::bb8ServiceMessageResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::bb8_service_pkg::bb8ServiceMessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bb8_service_pkg/bb8ServiceMessageResponse";
  }

  static const char* value(const ::bb8_service_pkg::bb8ServiceMessageResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bb8_service_pkg::bb8ServiceMessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success    # Did it achieve it?\n"
;
  }

  static const char* value(const ::bb8_service_pkg::bb8ServiceMessageResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bb8_service_pkg::bb8ServiceMessageResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bb8ServiceMessageResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bb8_service_pkg::bb8ServiceMessageResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bb8_service_pkg::bb8ServiceMessageResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BB8_SERVICE_PKG_MESSAGE_BB8SERVICEMESSAGERESPONSE_H
