(cl:defpackage bb8_service_pkg-srv
  (:use )
  (:export
   "BB8SERVICEMESSAGE"
   "<BB8SERVICEMESSAGE-REQUEST>"
   "BB8SERVICEMESSAGE-REQUEST"
   "<BB8SERVICEMESSAGE-RESPONSE>"
   "BB8SERVICEMESSAGE-RESPONSE"
  ))

