(cl:defpackage bb8_action_pkg-msg
  (:use )
  (:export
   "<CUSTOMACTIONMSGACTION>"
   "CUSTOMACTIONMSGACTION"
   "<CUSTOMACTIONMSGACTIONFEEDBACK>"
   "CUSTOMACTIONMSGACTIONFEEDBACK"
   "<CUSTOMACTIONMSGACTIONGOAL>"
   "CUSTOMACTIONMSGACTIONGOAL"
   "<CUSTOMACTIONMSGACTIONRESULT>"
   "CUSTOMACTIONMSGACTIONRESULT"
   "<CUSTOMACTIONMSGFEEDBACK>"
   "CUSTOMACTIONMSGFEEDBACK"
   "<CUSTOMACTIONMSGGOAL>"
   "CUSTOMACTIONMSGGOAL"
   "<CUSTOMACTIONMSGRESULT>"
   "CUSTOMACTIONMSGRESULT"
  ))

