; Auto-generated. Do not edit!


(cl:in-package bb8_action_pkg-msg)


;//! \htmlinclude CustomActionMsgResult.msg.html

(cl:defclass <CustomActionMsgResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:string
    :initform ""))
)

(cl:defclass CustomActionMsgResult (<CustomActionMsgResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CustomActionMsgResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CustomActionMsgResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name bb8_action_pkg-msg:<CustomActionMsgResult> is deprecated: use bb8_action_pkg-msg:CustomActionMsgResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <CustomActionMsgResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader bb8_action_pkg-msg:result-val is deprecated.  Use bb8_action_pkg-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CustomActionMsgResult>) ostream)
  "Serializes a message object of type '<CustomActionMsgResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'result))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'result))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CustomActionMsgResult>) istream)
  "Deserializes a message object of type '<CustomActionMsgResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'result) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'result) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CustomActionMsgResult>)))
  "Returns string type for a message object of type '<CustomActionMsgResult>"
  "bb8_action_pkg/CustomActionMsgResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CustomActionMsgResult)))
  "Returns string type for a message object of type 'CustomActionMsgResult"
  "bb8_action_pkg/CustomActionMsgResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CustomActionMsgResult>)))
  "Returns md5sum for a message object of type '<CustomActionMsgResult>"
  "c22f2a1ed8654a0b365f1bb3f7ff2c0f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CustomActionMsgResult)))
  "Returns md5sum for a message object of type 'CustomActionMsgResult"
  "c22f2a1ed8654a0b365f1bb3f7ff2c0f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CustomActionMsgResult>)))
  "Returns full string definition for message of type '<CustomActionMsgResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CustomActionMsgResult)))
  "Returns full string definition for message of type 'CustomActionMsgResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CustomActionMsgResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'result))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CustomActionMsgResult>))
  "Converts a ROS message object to a list"
  (cl:list 'CustomActionMsgResult
    (cl:cons ':result (result msg))
))
